repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: master
    hooks:
      - id: isort
        additional_dependencies:
          - toml
  # use system python to avoid --ignore-missing-imports due to uninstalled packages
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        types: [python]
        files:
          ^vbf_parser/
        entry: mypy