repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/timothycrosley/isort
    rev: master
    hooks:
      - id: isort
        additional_dependencies:
          - toml
