repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: master
    hooks:
      - id: isort
        additional_dependencies:
          - toml
  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.7.9'
    hooks:
      - id: flake8
  - repo: local
    hooks:
      # use system python to avoid --ignore-missing-imports due to uninstalled packages
      - id: mypy
        name: mypy
        language: system
        types: [python]
        files:
          ^vbf_parser/
        entry: mypy
      - id: xenon
        name: xenon
        language: python
        additional_dependencies: [xenon]
        types: [python]
        entry: xenon -bC -aA vbf_parser/
