language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install pytest coverage mypy black
script:
  - coverage run -m pytest --doctest-modules
  - mypy vbf_parser
  - black --check --diff vbf_parser
after_success:
  - bash <(curl -s https://codecov.io/bash)