language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install pytest coverage
script:
  - coverage run -m pytest --doctest-modules
after_success:
  - bash <(curl -s https://codecov.io/bash)