language: python
cache:
  pip: true
  directories:
    - /home/travis/.cache/pre-commit
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov coverage mypy pre-commit bandit
script:
  - pytest --cov=vbf_parser --doctest-modules
  - pre-commit run --all-files
  - bandit -c .bandit.yml -r vbf_parser
after_success:
  - bash <(curl -s https://codecov.io/bash)